### ISSUE TITLE
Preliminary module plan

### ISSUE THREAD

**Issue by FelixKrueger** [nf-core/riboseq#1]
### Description of feature

This issue is recreated from @JackCurragh's module plan (the issues wouldn't transfer over).
Here is attempt to break down the required/desired modules for each processing stage of the workflow:

### Pre-Processing
 
--- 

- [x] Quality Control (FastQC)
--- 

- [x] Cutadapt (Adapter Removal)
- [ ] FASTP (Adapter Removal)

--- 
- [x]  UMI-tools (UMI handling)
--- 

- [ ]  Bowtie 1 (rRNA removal)
- [x]  HISAT2 (rRNA removal)
- [ ]  RiboDetector
- [ ]  SortMeRNA

### Alignment

- [ ] STAR (Genome Alignment)
- [x] HISAT2 (Genome Alignment)
- [ ] Bowtie (Transcriptome Alignment)

---

- [x] Samtools (Alignment processing)
- [x] BEDtools (Alignment processing)

### Translated ORF Detection
- [ ] RiboCode
- [ ] RiboTaper
- [ ] Ribo-TISH
- [ ] Ribotricer
- [ ] ORFik

### Quantification
 
- [ ] Salmon (Pusedoalignment + Quantification)
- [x]  featurecoutns (Quantification)
- [ ]  RiboCode/ORFcount

### Differential Expression

- [ ]  Riborex (DE) (DEseq2, EdgeR, Voom)
- [ ]  Anota2Seq (DE)
- [ ]  DeltaTE (DE)

Please reply here with any other packages we should consider!

**Comment by FelixKrueger** [comment]
Caroline (@Caroline-99) commented:

> Yeah I think the module plan is very good, thank you for doing it. We could also integrate subsampling at the start of the pipeline. Ed had proposed this for my dissertation, but I couldn't do it it due to time constraints. I have now added FASTP to our pipeline and am in the process of implementing subworkflows. Once I get it working, I will update everything on github.

**Comment by pinin4fjords** [comment]
Strategy has shifted somewhat on this with the Altos/ Seqera push on Riboseq. I'm going to close this issue, but pull things from it as I define issues on a new V1 release milestone.
