### ISSUE TITLE
Add ribotricer/prepareorfs

### ISSUE THREAD

**Issue by pinin4fjords** [nf-core/riboseq#18]
### Description of feature

Add module for generating candidate orf list for Ribotricer- processes, first in nf-core/modules, then here. See https://github.com/smithlabcode/ribotricer?tab=readme-ov-file#preparing-candidate-orfs.

**Comment by JackCurragh** [comment]
@pinin4fjords looks like you have taken care of this. Can reopen if I misunderstood
